### ISSUE TITLE
possible string overflow in portable.c

### ISSUE THREAD

**Issue by seismopaul** [iris-edu/libdali#2]
It seems the newer compiler is highlighting a potential overflow in libdali:

portable.c:667:5: note: 'snprintf' output between 2 and 130 bytes into a destination of size 100

I just fixed it in EW SVN...

pauls-MacBook-Air-3:libdali paulf$ svn commit -m "fixed a potential string overflow in libdali" portable.c

Sending        portable.c

Transmitting file data .

Committed revision 7927.

pauls-MacBook-Air-3:libdali paulf$

**Comment by chad-earthscope** [comment]
Fixed, thanks @seismopaul
